pipeline {
    agent any
    
    tools {
      terraform 'Terraform'
      }

    stages {
        stage('Clean workspace') {
            steps {
             cleanWs()
            }
        }
        stage('Terraform init') {
            steps { 
                script {
                    //sh 'cd ${WORKSPACE}/vpc'
                    dir('vpc') {
                    sh 'terraform init'
                    }    
                }
            }
        }
    }
}
