pipeline {
    agent any
    
    tools {
      terraform 'Terraform'
      }

    stages {
        stage ('Clean Workspace') {
            steps {
              cleanWs()
              }
           }
           
        stage('Terraform init') {
            steps { 
                script {
                    sh 'cd ${WORKSPACE}/vpc'
                }
            }
        }
    }
}
