pipeline {
    agent any
    
    tools {
      terraform 'Terraform'
      }

    stages {
        stage('Terraform init') {
            steps { 
                script {
                    //sh 'cd ${WORKSPACE}/vpc'
                    sh 'terraform init'
                }
            }
        }
    }
}
