pipeline {
    agent any
    
    tools {
      terraform 'Terraform'
      }

    stages {
        stage('Terraform init') {
            steps { 
                script {
                    sh '''
                      cd vpc
                      terraform init
                '''
                }
            }
        }       
        
        stage('Terraform apply') {
            steps { 
                script {
                    sh '''
                      terraform apply -auto-approve
                '''
                }
            }
        }
    }
}
